server.port: 8080
server.error.include-message: ALWAYS

info:
  app:
    name: "java-sat-recruitment"
    description: "This is a simple API to create users"
    version: 1.0

users:
  path: "/users.txt"
  maxMoneyValue: 100
  minMoneyValue: 10
  normal:
    maxPercentage: 0.12
    minPercentage: 0.8
  premium:
    maxPercentage: 2
  super:
    maxPercentage: 0.2


